"use client";

import { AlertTriangle, Download, RotateCcw } from "lucide-react";
import { useMemo, useState } from "react";
import { Badge, Button, Card, StatCard } from "@/components/ui";
import { recordAuditEvent } from "@/lib/audit-log";
import { defaultChecklistInput, generateChecklist } from "@/lib/checklist-rules";
import type {
  ApplicationType,
  ChecklistInput,
  CollateralType,
  CustomerType,
  DocumentCategory,
  FacilityType,
  FinancialStatementStatus,
  RequirementLevel,
  RiskLevel
} from "@/lib/types";
import { downloadCsv, toCsv } from "@/lib/utils";

const applicationTypes: ApplicationType[] = ["New", "Renewal", "Enhancement"];
const facilityTypes: FacilityType[] = ["Term Loan", "Overdraft", "Trade Line", "Bank Guarantee"];
const collateralTypes: CollateralType[] = [
  "Property",
  "Cash Deposit",
  "Fixed Deposit",
  "Corporate Guarantee",
  "Personal Guarantee",
  "Debenture",
  "Unsecured"
];
const customerTypes: CustomerType[] = ["Individual", "Sole Proprietor", "Partnership", "SME Company", "Corporate"];
const riskLevels: RiskLevel[] = ["Low", "Medium", "High"];
const financialStatuses: FinancialStatementStatus[] = ["Available", "Not Available", "Waiver Requested"];
const categories: Array<DocumentCategory | "All"> = [
  "All",
  "General",
  "Financial",
  "Facility",
  "Collateral",
  "Compliance / Control"
];

function SelectField<T extends string>({
  label,
  value,
  options,
  onChange
}: {
  label: string;
  value: T;
  options: T[];
  onChange: (value: T) => void;
}) {
  return (
    <label className="grid gap-2 text-sm font-medium">
      {label}
      <select className="control" value={value} onChange={(event) => onChange(event.target.value as T)}>
        {options.map((option) => (
          <option key={option} value={option}>
            {option}
          </option>
        ))}
      </select>
    </label>
  );
}

function requirementTone(level: RequirementLevel) {
  if (level === "Required") {
    return "danger";
  }
  if (level === "Conditional") {
    return "warning";
  }
  return "default";
}

export function DocumentChecklistGenerator() {
  const [input, setInput] = useState<ChecklistInput>(defaultChecklistInput);
  const [category, setCategory] = useState<DocumentCategory | "All">("All");

  const result = useMemo(() => generateChecklist(input), [input]);
  const filteredDocuments = result.documents.filter((document) => category === "All" || document.category === category);
  const requiredCount = result.documents.filter((document) => document.requirementLevel === "Required").length;
  const conditionalCount = result.documents.filter((document) => document.requirementLevel === "Conditional").length;
  const optionalCount = result.documents.filter((document) => document.requirementLevel === "Optional").length;

  const updateInput = <K extends keyof ChecklistInput>(key: K, value: ChecklistInput[K]) => {
    setInput((current) => ({ ...current, [key]: value }));
  };

  const exportChecklist = () => {
    downloadCsv(
      "gccm-document-checklist.csv",
      toCsv(
        result.documents.map((document) => ({
          id: document.id,
          name: document.name,
          category: document.category,
          requirementLevel: document.requirementLevel,
          businessRuleId: document.businessRuleId,
          reason: document.reason
        }))
      )
    );
    recordAuditEvent({
      actor: "RM / BA Reviewer",
      action: "Checklist exported",
      module: "Document Checklist",
      referenceId: `${input.applicationType} ${input.facilityType}`,
      details: `Exported ${result.documents.length} documents for ${input.applicationType}, ${input.facilityType}, ${input.collateralType}, ${input.riskLevel} risk.`,
      controlImpact: result.warnings.length > 0 ? "High" : "Medium"
    });
  };

  const resetChecklist = () => {
    setInput(defaultChecklistInput);
    setCategory("All");
    recordAuditEvent({
      actor: "RM / BA Reviewer",
      action: "Checklist inputs reset",
      module: "Document Checklist",
      referenceId: "DEFAULT",
      details: "Checklist inputs were reset to the default New Term Loan with Property collateral scenario.",
      controlImpact: "Low"
    });
  };

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <StatCard label="Total Documents" value={result.documents.length} helper="Generated by rule engine" />
        <StatCard label="Required" value={requiredCount} tone="danger" helper="Submission control items" />
        <StatCard label="Conditional" value={conditionalCount} tone="warning" helper="Depends on case context" />
        <StatCard label="Optional" value={optionalCount} helper="Supporting evidence" />
      </div>

      <div className="grid gap-6 xl:grid-cols-[360px_minmax(0,1fr)]">
        <Card>
          <div className="flex items-start justify-between gap-4">
            <div>
              <h2 className="text-lg font-semibold">Application Inputs</h2>
              <p className="mt-1 text-sm text-muted-foreground">The output changes when business context changes.</p>
            </div>
            <Button onClick={resetChecklist} variant="ghost">
              <RotateCcw className="h-4 w-4" />
              Reset
            </Button>
          </div>

          <div className="mt-5 grid gap-4">
            <SelectField label="Application Type" value={input.applicationType} options={applicationTypes} onChange={(value) => updateInput("applicationType", value)} />
            <SelectField label="Facility Type" value={input.facilityType} options={facilityTypes} onChange={(value) => updateInput("facilityType", value)} />
            <SelectField label="Collateral Type" value={input.collateralType} options={collateralTypes} onChange={(value) => updateInput("collateralType", value)} />
            <SelectField label="Customer Type" value={input.customerType} options={customerTypes} onChange={(value) => updateInput("customerType", value)} />
            <SelectField label="Risk Level" value={input.riskLevel} options={riskLevels} onChange={(value) => updateInput("riskLevel", value)} />
            <SelectField label="Financial Statement" value={input.financialStatementStatus} options={financialStatuses} onChange={(value) => updateInput("financialStatementStatus", value)} />
          </div>
        </Card>

        <div className="space-y-6">
          {result.warnings.length > 0 ? (
            <Card className="border-warning/40 bg-warning/10">
              <div className="flex gap-3">
                <AlertTriangle className="mt-1 h-5 w-5 text-warning-foreground dark:text-warning" />
                <div>
                  <h2 className="font-semibold">Risk Warning</h2>
                  <ul className="mt-2 space-y-1 text-sm text-muted-foreground">
                    {result.warnings.map((warning) => (
                      <li key={warning}>{warning}</li>
                    ))}
                  </ul>
                </div>
              </div>
            </Card>
          ) : null}

          <Card>
            <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
              <div>
                <h2 className="text-lg font-semibold">Generated Checklist</h2>
                <p className="mt-1 text-sm text-muted-foreground">Documents are grouped by category with rule rationale.</p>
              </div>
              <div className="flex flex-wrap gap-2">
                <select className="control" value={category} onChange={(event) => setCategory(event.target.value as DocumentCategory | "All")}>
                  {categories.map((item) => (
                    <option key={item} value={item}>
                      {item}
                    </option>
                  ))}
                </select>
                <Button onClick={exportChecklist} variant="secondary">
                  <Download className="h-4 w-4" />
                  Export
                </Button>
              </div>
            </div>

            <div className="mt-5 overflow-x-auto rounded-lg border">
              <table className="w-full min-w-[880px] border-collapse text-sm">
                <thead className="table-head">
                  <tr>
                    <th className="px-4 py-3 text-left">Document</th>
                    <th className="px-4 py-3 text-left">Category</th>
                    <th className="px-4 py-3 text-left">Level</th>
                    <th className="px-4 py-3 text-left">Rule</th>
                    <th className="px-4 py-3 text-left">Reason</th>
                  </tr>
                </thead>
                <tbody>
                  {filteredDocuments.map((document) => (
                    <tr className="border-t align-top" key={document.id}>
                      <td className="px-4 py-3 font-medium">{document.name}</td>
                      <td className="px-4 py-3 text-muted-foreground">{document.category}</td>
                      <td className="px-4 py-3">
                        <Badge tone={requirementTone(document.requirementLevel)}>{document.requirementLevel}</Badge>
                      </td>
                      <td className="px-4 py-3 text-muted-foreground">{document.businessRuleId}</td>
                      <td className="px-4 py-3 text-muted-foreground">{document.reason}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Card>

          <Card>
            <h2 className="text-lg font-semibold">Triggered Business Rules</h2>
            <div className="mt-4 grid gap-3 md:grid-cols-2">
              {result.triggeredRules.map((item) => (
                <div className="rounded-lg border p-4" key={item.id}>
                  <div className="flex items-center justify-between gap-3">
                    <h3 className="font-semibold">{item.id}</h3>
                    <Badge tone="info">{item.controlPoint}</Badge>
                  </div>
                  <p className="mt-2 text-sm font-medium">{item.title}</p>
                  <p className="mt-1 text-sm text-muted-foreground">{item.description}</p>
                </div>
              ))}
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
}
